add theme

diff --git a/.chezmoiscripts/run_once_05-create-folder-structure.sh.tmpl b/.chezmoiscripts/run_once_05-create-folder-structure.sh.tmpl
--- a/.chezmoiscripts/run_once_05-create-folder-structure.sh.tmpl
+++ b/.chezmoiscripts/run_once_05-create-folder-structure.sh.tmpl
@@ -4,4 +4,8 @@ echo "Create folder structure"
 
 mkdir -p ~/projects
 cd ~/projects
-gh repo clone ryansearch
+
+folder="ryansearch"
+if ! gh repo clone "${folder}" 2>/dev/null && [ -d "${folder}" ] ; then
+    echo "Clone failed because the folder ${folder} exists"
+fi
